# -------------------
# Jekyll Config
# --------------------
baseurl: "/website"
url: ""
permalink: pretty
markdown: kramdown
highlighter: rouge
collections_dir: collections

# Plugins
plugins:
  - jekyll-environment-variables
  - jekyll-paginate

paginate: 6
paginate_path: "/blog/page/:num"

collections:
  services:
    output: true
    permalink: /:collection/:path/
  projects:
    output: true
    permalink: /:collection/:path/
  team:
    output: true
    permalink: /:collection/:path/
  posts:
    output: true
    permalink: /blog/:path/

defaults:
  - scope:
      path: ""
      type: services
    values:
      layout: service
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  - scope:
      path: ""
      type: posts
    values:
      layout: post
      weight: 999
  - scope:
      path: "images"
    values:
      image: true
  - scope:
      path: "categories"
    values:
      permalink: /category/:basename/
  - scope:
      path: "pages"
    values:
      permalink: /:basename/

# SCSS
sass:
  style: compact

# Excludes
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - netlify.toml


# -------------------
# Theme Config
# --------------------
title: "iTech Electronics - Serwis elektroniki przemysłowej"
category_dir: category

colors:
  #light-mode colors
  primary: "#00B6FF"
  primary_2: "#000000"
  primary_text: "#fdfcf9"
  secondary: "#8215cb"
  background: "#0f0f10"
  background_2: "#1a191c"
  background_3: "#222124"
  text: "#f5f5ec"
  text_2: "#b6c3d6"

  # dark-mode colors
  primary_dark: "#00B6FF"
  primary_2_dark: "#000000"
  primary_text_dark: "#fdfcf9"
  secondary_dark: "#8215cb"
  background_dark: "#0f0f10"
  background_2_dark: "#1a191c"
  background_3_dark: "#222124"
  text_dark: "#f5f5ec"
  text_2_dark: "#b6c3d6"


fonts:
  google_fonts: "https://fonts.googleapis.com/css2?family=Fira+Mono&family=Lato:wght@300;400;700&family=Source+Sans+Pro:wght@300;400;700&display=swap"
  heading: "Lato"
  base: "Source Sans Pro"
  monospace: "Fira Mono"
  logo: "Lato"

logo:
  logo_text: "iTech Electronics"
  logo_image: assets/images/logo/logo.png
  logo_image_mobile: assets/images/logo/logo-mobile.png
  logo_image_invert: assets/images/logo/logo-invert.png
  logo_image_invert_mobile: assets/images/logo/logo-invert-mobile.png
  logo_image_desktop_height: "55px"
  logo_image_desktop_width: "55px"
  logo_image_mobile_height: "30px"
  logo_image_mobile_width: "30px"
  show_logo_image_on_mobile: true
  show_logo_image_on_desktop: true
  show_logo_text_on_mobile: true
  show_logo_text_on_desktop: true

header:
  fixed: true

darkmode:
  enable_dark_mode: true
  show_dark_mode_toggle_in_header: false
  show_dark_mode_toggle_in_bottom: false
  show_dark_mode_toggle_in_mobile_menu: false

analytics:
  google_analytics_id: ""

disqus:
  shortname: "" # Your disqus shortcode. leave this blank to disable comments globally

mailchimp:
  form_action_url: 

contact_form:
  use_netlify_form: false
  use_formspree_form: false
  formspree_endpoint: https://formspree.io/f/moqyklqv

menu:
  show_dropdown_items_in_mobile_menu: false
  show_social_media_in_mobile_menu: true

footer:
  enable_footer: true # show/hide the entire footer
  footer_title: "iTech Electronics"
  footer_description: "Serwis elektroniki przemysłowej"
  enable_social_media_icons: true
  enable_contact_details: true
  enable_menu_footer_primary: true
  enable_menu_footer_secondary: true
  enable_menu_footer_tertiary: false
  footer_primary_menu_title: ""
  footer_secondary_menu_title: " "
  footer_tertiary_menu_title: ""

bottom:
  enable_bottom: true # show/hide the entire bottom (below the footer)
  enable_bottom_menu: true # if enabled, the bottom menu can be edited in `_data/menu.yml`
  copyright_text: "© 2023 iTech Electronics"

sidebar:
  enable_sidebar_services: true
  enable_breadcrumbs_services: true
  enable_sidebar_projects: true
  enable_breadcrumbs_projects: true
